name: Temperature
version: '${project.version}'
main: rama.spigot.Temperature
api-version: '1.20'
load: STARTUP
commands:
  temperature:
    description: "Temperature main command."
depend:
  - PlaceholderAPI
